### ISSUE TITLE
avro schema validation

### ISSUE THREAD

**Issue by gangadhar01a** [fastavro/fastavro#333] opened 2019-05-03 16:58 UTC
We are using fastavro to validate the syntax of the avro schema, for this purpose we are using the factavro module. 

"avrolint.py"  loads the fastavro module and throws if there are any exceptions. This works for any generic date types (string, int etc...), except for the customized type (example: com.hautelook.halo-www.order.service.Money) which has been listed in below example. 

Though the schema has the valid syntax, it's throwing a following exception 
"_fastavro._schema_common.UnknownType: com.hautelook.halo-www.order.service.Money_"

**avrolint.py**

_#!/usr/bin/env python3
import fastavro
import sys

try:
    test = fastavro.schema.load_schema(sys.argv[1])
    print(test)
except Exception as e:
    print("Error {}".format(e))
    raise_

Schema to check 
**test.avsc** 
_{
  "type" : "record",
  "namespace" : "com.hautelook.halo-www.order.service",
  "name": "FreightData",
  "fields": [
    {"name": "freightSubtotal", "type": "com.hautelook.halo-www.order.service.Money"},
    {"name": "freightTaxes", "type": "com.hautelook.halo-www.order.service.Money"},
    {"name": "freightDiscount", "type": "com.hautelook.halo-www.order.service.Money"},
    {"name": "freightTotal", "type": "com.hautelook.halo-www.order.service.Money"}
  ]
}_

**l874-c02rp479g8wn:Desktop gangahdar.reddy$ **python3 avro.py test.avsc** 
**Error com.hautelook.halo-www.order.service.Money**
Traceback (most recent call last):
  File "fastavro/_schema.pyx", line 205, in fastavro._schema._load_schema
  File "fastavro/_schema.pyx", line 193, in fastavro._schema.load_schema
FileNotFoundError: [Errno 2] No such file or directory: 'com.hautelook.halo-www.order.service.Money.avsc**'

**During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "avro.py", line 7, in <module>
    test = fastavro.schema.load_schema(sys.argv[1])
  File "fastavro/_schema.pyx", line 196, in fastavro._schema.load_schema
  File "fastavro/_schema.pyx", line 207, in fastavro._schema._load_schema
  File "fastavro/_schema.pyx", line 201, in fastavro._schema._load_schema
  File "fastavro/_schema.pyx", line 59, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 143, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 180, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 76, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: com.hautelook.halo-www.order.service.Money**

**Comment by scottbelden** [comment] 2019-05-03 18:29
Where is `com.hautelook.halo-www.order.service.Money` defined? The avro specification says that a named type must be defined before it is used in a schema.

**Comment by scottbelden** [comment] 2019-05-12 19:14
@gangadhar01a I forgot to mention you on my question. Did you see it?

**Comment by scottbelden** [comment] 2019-06-27 15:17
I'm going to close this as I can't reproduce it. Feel free to open a new issue with a way to reproduce the error if it still exists.

**Closed by scottbelden** 2019-06-27 15:17 UTC
