### ISSUE TITLE
fastavro installation throwing wheels error

### ISSUE THREAD

**Issue by shubhank-saxena** [fastavro/fastavro#708] opened 2023-08-09 06:00 UTC
Hello!
I am trying to install fastavro as a dependency on my google cloud run instance (via docker) but it has been throwing this error recently.

```
Building wheels for collected packages: fastavro, psycopg2
  Building wheel for fastavro (pyproject.toml): started
  Building wheel for fastavro (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for fastavro (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [157 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/types.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_write_py.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_schema_common.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/const.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/logical_writers.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_schema_py.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_read_common.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/schema.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_validate_common.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/json_write.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_validation_py.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/utils.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/logical_readers.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/__main__.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_read_py.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/__init__.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/read.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/validation.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_write_common.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/json_read.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_logical_writers_py.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/_logical_readers_py.py -> build/lib.linux-x86_64-cpython-311/fastavro
      copying fastavro/write.py -> build/lib.linux-x86_64-cpython-311/fastavro
      creating build/lib.linux-x86_64-cpython-311/fastavro/io
      copying fastavro/io/binary_decoder.py -> build/lib.linux-x86_64-cpython-311/fastavro/io
      copying fastavro/io/json_decoder.py -> build/lib.linux-x86_64-cpython-311/fastavro/io
      copying fastavro/io/json_encoder.py -> build/lib.linux-x86_64-cpython-311/fastavro/io
      copying fastavro/io/__init__.py -> build/lib.linux-x86_64-cpython-311/fastavro/io
      copying fastavro/io/binary_encoder.py -> build/lib.linux-x86_64-cpython-311/fastavro/io
      copying fastavro/io/parser.py -> build/lib.linux-x86_64-cpython-311/fastavro/io
      copying fastavro/io/symbols.py -> build/lib.linux-x86_64-cpython-311/fastavro/io
      creating build/lib.linux-x86_64-cpython-311/fastavro/repository
      copying fastavro/repository/base.py -> build/lib.linux-x86_64-cpython-311/fastavro/repository
      copying fastavro/repository/flat_dict.py -> build/lib.linux-x86_64-cpython-311/fastavro/repository
      copying fastavro/repository/__init__.py -> build/lib.linux-x86_64-cpython-311/fastavro/repository
      copying fastavro/py.typed -> build/lib.linux-x86_64-cpython-311/fastavro
      running build_ext
      Compiling fastavro/_read.pyx because it changed.
      [1/1] Cythonizing fastavro/_read.pyx

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  writer_schema, named_schemas, offset, size, return_record_name, return_record_name_override
              )


      class Block:
          def __init__(
          ^
      ------------------------------------------------------------

      fastavro/_read.pyx:972:4: Compiler crash in AnalyseDeclarationsTransform

      File 'ModuleNode.py', line 203, in analyse_declarations: ModuleNode(_read.pyx:1:0,
          doc = 'Python code for reading AVRO files',
          full_module_name = 'fastavro._read')
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:10:0)
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:971:0)
      File 'Nodes.py', line 5121, in analyse_declarations: PyClassDefNode(_read.pyx:971:0,
          name = 'Block')
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(_read.pyx:972:4)
      File 'Nodes.py', line 2710, in analyse_declarations: CFuncDefNode(_read.pyx:972:4,
          args = [...]/11,
          modifiers = [...]/0,
          outer_attrs = [...]/2,
          overridable = True,
          visibility = 'private')
      File 'Nodes.py', line 2721, in declare_cpdef_wrapper: CFuncDefNode(_read.pyx:972:4,
          args = [...]/11,
          modifiers = [...]/0,
          outer_attrs = [...]/2,
          overridable = True,
          visibility = 'private')
      File 'Nodes.py', line 2787, in call_self_node: CFuncDefNode(_read.pyx:972:4,
          args = [...]/11,
          modifiers = [...]/0,
          outer_attrs = [...]/2,
          overridable = True,
          visibility = 'private')

      Compiler crash traceback from this point on:
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 2787, in call_self_node
          type_entry = self.type.args[0].type.entry
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: 'PyObjectType' object has no attribute 'entry'
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 37, in <module>
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 349, in run
          self.run_command("build")
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-c_i74iax/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: fastavro/_read.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fastavro
  Building wheel for psycopg2 (setup.py): started
  Building wheel for psycopg2 (setup.py): finished with status 'done'
  Created wheel for psycopg2: filename=psycopg2-2.9.6-cp311-cp311-linux_x86_64.whl size=495093 sha256=66db60affc8b7376b8396365341051b9e46d0dcc54d2649205d8222e5113d013
  Stored in directory: /tmp/pip-ephem-wheel-cache-90x1w_ch/wheels/a2/c5/3d/b8fd44767c125a321b8d6d7fbcce0181d2f2d1e34967c81365
Successfully built psycopg2
Failed to build fastavro
ERROR: Could not build wheels for fastavro, which is required to install pyproject.toml-based projects
```

I haven't changed any piece of code. There has been no change in dockerfile and the requirements and versions are un-touched.
Version - `1.5.4`
pandavro - `1.7.2`

Thank you!

**Comment by scottbelden** [comment] 2023-08-09 09:50
This is a duplicate of https://github.com/fastavro/fastavro/issues/701.

The change is that something is now installing Cython 3. There are two solutions:

- Use `fastavro>=1.8.1`
- Use the workaround mentioned here: https://github.com/fastavro/fastavro/issues/701#issuecomment-1639051800
  - pip install setuptools wheel 'Cython<3'
  - pip install --no-build-isolation fastavro==1.5.4

**Closed by scottbelden** 2023-08-09 09:50 UTC
