### ISSUE TITLE
Issue with LONG and INT columns when extracting from Oracle

### ISSUE THREAD

**Issue by oyamin** [fastavro/fastavro#280] opened 2018-10-02 00:21 UTC
Hello,

I am extracting data from oracle and generating avro schema based on column types from cx_Oracle. I have the following:

`
if defaultType == cx_Oracle.NUMBER:

    type = {
        "name": name,
        "type": ["null", {"name": name, "type": "long"}]
    }
    avro_schema.append(type)
`
The main issue is that output_type_handler in cx_oracle puts LONG and INT under NUMBER datatype (or at least that's how dba had the tables setup). When trying to generate the avro file with the schema and I encounter an INT column, I get the following error:

`
ValueError: 3453453453532423323L (type <type 'long'>) do not match ['null', {'type': 'long'}]
`

So i tried to convert all int and long to decimal:

`
if defaultType == cx_Oracle.NUMBER:

    type = {
        "name": name,
        "type": ["null", {"name": name, "type": "bytes", "logicalType": "decimal", "precision": 38, "scale": 0}]
    }
    avro_schema.append(type)
`

and i get error (i also tried replacing bytes with long) and same issue:

with long:

`
ValueError: 3453453453532423323L (type <type 'long'>) do not match [{'logicalType': 'decimal', 'scale': 0, 'type': 'long', 'precision': 38}, 'null']
`

with bytes:

`
ValueError: 3453232446456443 (type <type 'int'>) do not match [{'logicalType': 'decimal', 'scale': 0, 'type': 'bytes', 'precision': 38}, 'null']
`

Please let me know if there is any way around this.

I am using 
python==2.7.12
fastavro==0.21.5
cx-Oracle==6.2

Thank you.

**Comment by scottbelden** [comment] 2018-10-02 00:51
Do you have a script that I can run to get the error you are getting? I'm not sure what your full schema is or what data is being used.

**Comment by oyamin** [comment] 2018-10-02 01:00
I dont have it publicly available, because the code uses production data. But i can probably generate something simular with fake data.

**Comment by oyamin** [comment] 2018-10-02 01:18
To actually narrow down on the issue, seems that the problem is with one column where it contains mixed datatypes. Some numbers are long in that column like: 3453453453532423323L and some are just INT, like 3453232446456443.

So it seems that it is more of a mixed datatype issue.

**Comment by scottbelden** [comment] 2018-10-02 15:00
I'm still trying to reproduce this or figure out what you might be seeing. One thing that is confusing me is the part where you write:

```python
type = {
    "name": name,
    "type": ["null", {"name": name, "type": "long"}]
}
```

It seems like you are trying to define a record, but it's not doesn't have all the required information. Therefore, the `name` fields you have defined will be ignored.

**Comment by rhaarm** [comment] 2018-10-02 15:10
@oyamin 
My thoughts are if the data is coming back mixed try updating the schema. Also, there is no need for the name of a primitive type.
```
type = {
    "name": name,
    "type": ["null", "long", "int"]
}
```
Since order is "long" first, when extracting the data from an avro file, it may end up being represented as a "long" even if it was originally an "int". Thoughts on that? @scottbelden 

I'm beginning to wonder if there is something weird happening because of Python 2.7 long/int are different that Py3. Possibly an issue with the custom six library? @scottbelden

**Comment by oyamin** [comment] 2018-10-02 16:45
I don't have an customizations in six library. Makes sense, because int can be promoted to long. I tried adding ["null", "long", "int"] and got the following error:

"[\n  \"schematest.INTERNAL_COL is <9223444536456745645> of type <type 'long'> expected null\", \n  \"schematest.INTERNAL_COL is <9223444536456745645> of type <type 'long'> expected long\", \n  \"schematest.INTERNAL_COL is <9223444536456745645> of type <type 'long'> expected int\"\n]"

**Comment by oyamin** [comment] 2018-10-02 22:50
Also, updated and tried to use with python3.6.6 and got the same, but more detailed error:

  File "fastavro/_write.pyx", line 691, in fastavro._write.writer
  File "fastavro/_write.pyx", line 662, in fastavro._write.Writer.write
  File "fastavro/_validation.pyx", line 152, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 195, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 115, in fastavro._validation.validate_record
  File "fastavro/_validation.pyx", line 192, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 148, in fastavro._validation.validate_union
fastavro._validate_common.ValidationError: [
  "schematest.INTERNAL_COL is <9223444536456745645>  of type <class 'int'> expected null",
  "schematest.INTERNAL_COL is <9223444536456745645>  of type <class 'int'> expected long",
  "schematest.INTERNAL_COL is <9223444536456745645>  of type <class 'int'> expected int"
]

**Comment by rhaarm** [comment] 2018-10-02 22:55
There is another piece of the validation to verify the int size fits
between a specific number range. I'll take a look to see if that's causing
the problem.

**Comment by scottbelden** [comment] 2018-10-02 23:31
I looked at the `cx_Oracle` repo and they heavily use the C-API for their objects. I think what's going on is that the way they created their `NUMBER` type is such that it isn't a subclass of anything like `int` or `long` so our [`isinstance` checks here](https://github.com/fastavro/fastavro/blob/dcfa5614f0de787a2f89bb0f73bacb72209d5354/fastavro/_validation_py.py#L94) fail. However, they use the C API to return the correct `type` which is why I think we see the errors like `schematest.INTERNAL_COL is <9223444536456745645> of type <class 'int'> expected int`.

Of course, this is still pretty much speculation as I don't really know a way to stand up an oracle DB to be able to use their library and test with.

**Comment by oyamin** [comment] 2018-10-02 23:43
It seems that the number is too long. I updated the:
LONG_MIN_VALUE = -(1 << 63)
LONG_MAX_VALUE = (1 << 63) - 1
to
LONG_MIN_VALUE = -(1 << 64)
LONG_MAX_VALUE = (1 << 64) - 1

and it didn't give me the errors, but aborted with:

`OverflowError: Python int too large to convert to C long`

I also tried to convert it to decimal, but getting the same issue:

```
if defaultType == cx_Oracle.NUMBER:
                type = {
                    "name": name,
                    "type": ["null", {"type": "bytes", "logicalType": "decimal", "precision": 38, "scale": 0}]
                }
                FIELDS_LIST.append(type)
                return cursor.var(
                    str,
                    100,
                    outconverter=decimal.Decimal,
                    arraysize=cursor.arraysize)

```

but got back the usual error:

```
of type <class 'decimal.Decimal'> expected null\",
of type <class 'decimal.Decimal'> expected {'logicalType': 'decimal', 'precision': 38, 'scale': 0, 'type': 'long'}
```

**Comment by oyamin** [comment] 2018-10-03 00:00
Another thing I noticed is when i set the type to just:

"name": "testing"
"type": "long"

it does not error out for these records, but errors out for NoneType:

"[\n  \"Field(schematest.INTERNAL_COL) is None expected long\"\n]"

but after i change it to "type": ["long", "null"] or ["null", "long"], it comes back with the usuall error. As if it doesn't like the list of types.

**Comment by scottbelden** [comment] 2018-10-04 02:53
@oyamin Somewhere in your code where you have one of these `cx_Oracle.NUMBER` objects could you add the following prints and let me know what they return?

```python
# some_value is the cx_Oracle.NUMBER
print("isinstance({}, int) = {}".format(some_value, isinstance(some_value, int)))
print("isinstance({}, long) = {}".format(some_value, isinstance(some_value, long)))
import numbers
print("isinstance({}, numbers.Number) = {}".format(some_value, isinstance(some_value, numbers.Number)))
print("type({}) = {}".format(some_value, type(some_value)))


```

**Comment by scottbelden** [comment] 2019-07-09 19:00
I'm going to close this. I don't have a way to reproduce it and my suspicion is that they are using the C-API to create their `NUMBER` such that it claims to be `type <int>` but doesn't pass the `isinstance` test.

**Closed by scottbelden** 2019-07-09 19:00 UTC
