### ISSUE TITLE
type: "fixed" - fastavro._schema_common.UnknownType: fixed

### ISSUE THREAD

**Issue by oyamin** [fastavro/fastavro#268] opened 2018-09-12 21:36 UTC
I am trying to use fixed datatype when generating an Avro schema, but when I try to use it, I get an error.

Versions:

- Red Hat Enterprise Linux Server release 6.6
- Python 2.7.12
- fastavro==0.21.5

  
```
type = {
       "name": "testing",
       "type": "fixed",
       "size": 1
}

parsed_schema = parse_schema(schema)
  File "/usr/local/lib/python2.7/site-packages/fastavro/_schema_py.py", line 81, in parse_schema
    return _parse_schema(schema, "", _write_hint)
  File "/usr/local/lib/python2.7/site-packages/fastavro/_schema_py.py", line 165, in _parse_schema
    parse_field(field, namespace, _write_hint)
  File "/usr/local/lib/python2.7/site-packages/fastavro/_schema_py.py", line 202, in parse_field
    parsed_field["type"] = _parse_schema(field["type"], namespace, _write_hint)
  File "/usr/local/lib/python2.7/site-packages/fastavro/_schema_py.py", line 98, in _parse_schema
    raise UnknownType(schema)
fastavro._schema_common.UnknownType: fixed
```

I was able to bypass that error when I added "fixed" to PRIMITIVES dict in _schema_common.py but I am sure that is not how it should be since fixed is a complex type.

**Comment by scottbelden** [comment] 2018-09-12 21:52
Do you have a full script that reproduces this? When I try the following I don't have any errors:

```python
import fastavro
from io import BytesIO

schema = { 
    "name": "testing",
    "type": "fixed",
    "size": 1
}

data = b'a'
bio = BytesIO()

fastavro.writer(bio, schema, [data])

bio.seek(0)

for record in fastavro.reader(bio):
    print(record)
```

**Comment by rhaarm** [comment] 2018-09-12 21:58
@scottbelden I did a quick test, if you do a nested type, it fails.

`schema={"name": "testing", "type": {"type": "fixed", "size": 1}}`

**Comment by scottbelden** [comment] 2018-09-12 22:04
@rhaarm I don't think that's a valid schema. The `name` should be at the same level as `"type": "fixed"`. I tend to use [this site](https://json-schema-validator.herokuapp.com/avro.jsp) to do quick double checks on schemas and it also complains.

**Comment by rhaarm** [comment] 2018-09-12 22:10
Example from the Avro specifications, using "fixed" in a nested form.
```
{"type": "record", "name": "org.apache.avro.file.Header",
 "fields" : [
   {"name": "magic", "type": {"type": "fixed", "name": "Magic", "size": 4}},
   {"name": "meta", "type": {"type": "map", "values": "bytes"}},
   {"name": "sync", "type": {"type": "fixed", "name": "Sync", "size": 16}},
  ]
}
```

**Comment by scottbelden** [comment] 2018-09-12 22:12
Sure, but `Magic` and `Sync` are still `name`s at the same level of `"type": "fixed"`

**Comment by rhaarm** [comment] 2018-09-12 22:13
Maybe I'm looking at it wrong and first "name" & "type" are apart of "record" "field" definition and the extra nesting of "type" is separate.

**Comment by rhaarm** [comment] 2018-09-12 22:16
Ya looking at the website you referenced, it strips the Fixed Type Definition out and does a reference when it's all treated as a record.
```
{
  "definitions" : {
    "record:t" : {
      "type" : "object",
      "required" : [ "testing" ],
      "additionalProperties" : false,
      "properties" : {
        "testing" : {
          "$ref" : "#/definitions/fixed:testingFixed"
        }
      }
    },
    "fixed:testingFixed" : {
      "type" : "string",
      "pattern" : "^[\u0000-ÿ]*$",
      "minLength" : 1,
      "maxLength" : 1
    }
  },
  "$ref" : "#/definitions/record:t"
}
```

**Comment by scottbelden** [comment] 2018-09-12 22:18
@oyamin  Did you see my original reply? Do you have a full script that will reproduce the error?

**Comment by scottbelden** [comment] 2018-09-20 13:11
@oyamin I'm going to close this an I'm unable to reproduce. Please re-open or make a new issue if it's still a problem and there is a reliable way to reproduce it. Thanks.

**Closed by scottbelden** 2018-09-20 13:11 UTC
