### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 3: invalid start byte

### ISSUE THREAD

**Issue by metalshanked** [fastavro/fastavro#392] opened 2020-02-09 17:59 UTC
Python 3.7 on Linux fastavro (22.9) - Seem to be getting many unicode decode errors when parsing some avro's.  Is there an option to set encoding in the reader or a way for the reader to ignore the character and move on?

**Comment by scottbelden** [comment] 2020-02-10 12:13
Do you have an example avro file that you would be able to upload that I could check out? Or do you know how the file was created?

**Comment by metalshanked** [comment] 2020-02-13 23:03
Apologies, cannot obtain the sample to share. It is a Avro file from a vendor product. Is it possible that the data has non UTF8 encoding like 'Latin1' etc.  If so, is there a way to set the encoding option in fastavro?

**Comment by TuSKan** [comment] 2020-02-13 23:36
Did you open file with '**rb**' ?
```with open(avrofile, "rb") as f:```

**Comment by metalshanked** [comment] 2020-02-14 03:00
Yes, I opened as bytes with 'rb'.  fastavro reads fine for many of the lines until it comes across these non-utf characters and the reader object conks off.    

```   avro_reader = reader(f)
        for line_a in avro_reader:
            print (line_a)
```

After certain working lines...
```
Traceback
File "fastavro/_read.pyx", line 675, in _iter_avro_records
  File "fastavro/_read.pyx", line 557, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 452, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 555, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 427, in fastavro._read.read_union
  File "fastavro/_read.pyx", line 535, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 286, in fastavro._read.read_utf8
  File "fastavro/_six.pyx", line 22, in fastavro._six.py3_btou
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 2156: invalid continuation byte 
```

Wish I can do something like ```line.decode('latin1').encode('utf8',errors='replace')``` on the "avro_reader" object lines.

**Comment by scottbelden** [comment] 2020-02-14 03:44
Do you know which avro implementation was used to create the avro file? [According to the specification](https://avro.apache.org/docs/current/spec.html#binary_encoding) it mentions that strings should be UTF-8 character encoded:

```a string is encoded as a long followed by that many bytes of UTF-8 encoded character data.
For example, the three-character string "foo" would be encoded as the long value 3 (encoded as hex 06) followed by the UTF-8 encoding of 'f', 'o', and 'o' (the hex bytes 66 6f 6f):

06 66 6f 6f
```

**Comment by metalshanked** [comment] 2020-02-14 04:07
Not sure but I am guessing it could be a Java implementation since Java apps can read it without issue.  Also, Nvidia python cudf.read_avro() is able to read it as well.

**Comment by scottbelden** [comment] 2020-02-27 20:10
I spent some time trying to dig into this. I think I finally have a reproducible case. When running this script:

```python
from io import BytesIO

bio = BytesIO(b'Obj\x01\x02\x16avro.schema\x92\x03{"type":"record","name":"User","namespace":"example.avro","fields":[{"name":"name","type":"string"},{"name":"favorite_number","type":["int","null"]},{"name":"favorite_color","type":["string","null"]}]}\x00\x16\xc9;NV\xd8"_\x90=\xc2\xb6\x07\x06X\n\x04P\x0cAlyssa\x00\x80\x04\x02\x06Ben\x00\x0e\x00*red \xc2\xa4\xc2\xa4 \xe9dj\xc3\xa9\xc3\xa0\xe1\xba\xbf\xc3\xa8\x16\xc9;NV\xd8"_\x90=\xc2\xb6\x07\x06X\n')
bio.seek(0)

import fastavro

for record in fastavro.reader(bio):
    print(record)
```

This is the output:

```python
{'name': 'Alyssa', 'favorite_number': 256, 'favorite_color': None}
Traceback (most recent call last):
  File "error.py", line 8, in <module>
    for record in fastavro.reader(bio):
  File "/Users/sbelden/projects/fastavro/fastavro/_read_py.py", line 560, in _iter_avro_records
    return_record_name
  File "/Users/sbelden/projects/fastavro/fastavro/_read_py.py", line 433, in read_data
    return_record_name)
  File "/Users/sbelden/projects/fastavro/fastavro/_read_py.py", line 327, in read_record
    return_record_name)
  File "/Users/sbelden/projects/fastavro/fastavro/_read_py.py", line 433, in read_data
    return_record_name)
  File "/Users/sbelden/projects/fastavro/fastavro/_read_py.py", line 300, in read_union
    return read_data(decoder, idx_schema)
  File "/Users/sbelden/projects/fastavro/fastavro/_read_py.py", line 435, in read_data
    data = reader_fn(decoder, writer_schema, reader_schema)
  File "/Users/sbelden/projects/fastavro/fastavro/_read_py.py", line 192, in read_utf8
    return decoder.read_utf8()
  File "/Users/sbelden/projects/fastavro/fastavro/io/binary_decoder.py", line 81, in read_utf8
    return btou(self.read_bytes(), 'utf-8')
  File "/Users/sbelden/projects/fastavro/fastavro/six.py", line 21, in py3_btou
    return n.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 9: invalid continuation byte
```

The reason this happens is that I took a valid avro binary and did some manual modifications. Specifically in the script above, I changed `red \xc2\xa4\xc2\xa4 `**`g`**`dj\xc3\xa9` to `red \xc2\xa4\xc2\xa4 `**`\xe9`**`dj\xc3\xa9`.

When I try to read the file use the Java library in eclipse, it outputs the following:

```
{"name": "Alyssa", "favorite_number": 256, "favorite_color": null}
{"name": "Ben", "favorite_number": 7, "favorite_color": "red ¤¤ �djéàếè"}
```

This is all here mostly so I can remember my current thoughts for the next time I look at this issue. I haven't been able to use the java code to create a file like this under normal conditions and instead I had to do some manual hacking of the binary to get this error.

**Comment by scottbelden** [comment] 2021-11-30 15:36
Do you have a script that can reproduce the error? Or an avro file that produces the error? How was the avro file created? Using the Java library or something else?

I wasn't able to make much progress on this because there wasn't a lot of details to go on, but perhaps you can help fill in some of those details for me.

**Comment by scottbelden** [comment] 2021-12-02 00:36
Thanks for the update. I'm going to close this issue as I've never been able to reproduce it with a valid avro file.

**Closed by scottbelden** 2021-12-02 00:36 UTC
