### ISSUE TITLE
IndexError: list index out of range on Union datatype

### ISSUE THREAD

**Issue by matthiasdv** [fastavro/fastavro#464] opened 2020-08-13 21:21 UTC
**Issue**

Given an .avro file with a schema such as this one: 

```
{
    "name" : "some_field",
    "type" : [ "double", "null" ]
  },
```

See https://docs.oracle.com/database/nosql-12.1.3.1/GettingStartedGuide/avroschemas.html#unions under Unions. 

Fastavro throws the following error on read:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    dataframe = source.read()
  File "/venv/lib/python3.7/site-packages/intake_avro/source.py", line 132, in read
    return self._bag.compute()
  File "venv/lib/python3.7/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "venv/lib/python3.7/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "venv/lib/python3.7/site-packages/dask/multiprocessing.py", line 192, in get
    raise_exception=reraise, **kwargs)
  File "venv/lib/python3.7/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "venv/lib/python3.7/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "venv/lib/python3.7/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "venv/lib/python3.7/site-packages/dask/core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "venv/lib/python3.7/site-packages/dask/core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "venv/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "venv/lib/python3.7/site-packages/dask/bag/avro.py", line 158, in read_chunk
    return list(fastavro.iter_avro(i))
  File "fastavro/_read.pyx", line 810, in _iter_avro_records
  File "fastavro/_read.pyx", line 659, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 516, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 651, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 436, in fastavro._read.read_union
IndexError: list index out of range
```

Note that I have been able to export the full contents of the same Avro file to JSON using the Java avro tools utility. 

If needed I can provide a simple python project to reproduce. Any pointers on how to debug would be appreciated.

**Comment by scottbelden** [comment] 2020-08-14 00:03
If you could provide the avro file that would be great. Also, how are you writing the file?

**Comment by kkirsanov** [comment] 2020-08-16 06:48
_Thus, for unions containing "null", the "null" is usually listed first, since the default value of such unions is typically null.)_ (C) https://avro.apache.org/docs/1.10.0/spec.html#Unions

Try to move "null" forward

**Comment by scottbelden** [comment] 2020-09-02 20:18
I'm going to close this as there's no way for me to reproduce the issue. If you are able to provide the avro file or give more insight into how the file is being written then that could help locate the problem. Also, if you are able to use the apache python `avro` library to read it successfully that would be a good data point to have.

Feel free to re-open if you have additional details.

**Closed by scottbelden** 2020-09-02 20:18 UTC
