### ISSUE TITLE
zsh:segmentation fault

### ISSUE THREAD

**Issue by faker09** [fastavro/fastavro#539] opened 2021-04-27 02:05 UTC
when i using json_writer(), zsh:segmentation fault appear

**Comment by faker09** [comment] 2021-04-27 13:12
### **because my schema is so big, so i can't show in here---------(python3.9         kali linux latest           pip3 install fastavro)    
parsed_schema = parsed_schema(schema)
list_record = []
with open("A", 'rb') as fo, open("output.json","a") as output:
     avro_record = reader(fo, parsed_schema)
     for record in avro_record:
         list_record.append(record)
         if len(list_record) > 1000:
             json_writer(output, parsed_schema, list_record)
             list_record=[]
         else:
               pass

**Comment by scottbelden** [comment] 2021-04-27 13:58
Are you able to post the full stacktrace?

**Comment by scottbelden** [comment] 2021-05-14 13:53
I'm going to close this as there's not enough information and I can't reproduce the problem.

**Closed by scottbelden** 2021-05-14 13:53 UTC
