### ISSUE TITLE
Did fastavro lose support for streaming reader with PR #208 ?

### ISSUE THREAD

**Issue by jquast** [fastavro/fastavro#295] opened 2018-10-31 06:19 UTC
I've been scratching my head for some time over this one, I'm not sure if its a bug/regression or design choice, please advise -- if I build a program ``test.sh`` that contains:
```
cat some/avro_file.avro
```

And then execute this program::
```
import fastavro, subprocess
next(fastavro.reader(subprocess.Popen(['./test.sh'], stdout=subprocess.PIPE).stdout))
```
It raises exception in `_iter_avro_blocks`:

```
~/.pyenv/versions/3.6.6/envs/jupyter36/lib/python3.6/site-packages/fastavro/_read_py.py in _iter_avro_blocks(fo, header, codec, writer_schema, reader_schema)                                     
    543                                                                                          
    544     while True:                                                                          
--> 545         offset = fo.tell()                                                               
    546         try:                                                                             
    547             num_block_records = read_long(fo)                                            
                                                                                                 
OSError: [Errno 29] Illegal seek                                                                 
```

Reviewing PR #208 in detail, It looks like there is meant to be an option, *not* to use the block reader, can you advise @ryan-williams if that was the intent?

This line https://github.com/fastavro/fastavro/pull/208/files#diff-4393ec29a73aadf5c03299080aa0b819R597 in `_iter_avro_records`, appears to exist only to be distinguished from `_iter_avro_blocks`, for outer classes `reader` and `block_reader`, respectively.

However, `_iter_avro_blocks` uses the very same `_iter_avro_blocks` function, so it seems like a design choice to *only* support the new avro block reader, but this new function *requires the position to be known* which is not compatible with a stream.

**Comment by scottbelden** [comment] 2018-10-31 13:23
Good catch again. This is definitely an unintended regression (like the other with the `writer`). For a quick work around, we should be able to just have `_iter_avro_records` not call `_iter_avro_blocks` but instead implement the necessary logic without the calls to `tell()`.

It might also be possible to modify `_iter_avro_blocks` to not use `tell()` at all... the `size` variable appears to be just the sum of the long that is read, the `block_bytes`, and the `sync_marker`.

I can try to put in a PR for the first option (duplicate some logic) hopefully within the day and then look into trying to remove the need for the `tell()` a little later.

**Comment by jquast** [comment] 2018-10-31 20:02
Thanks @scottbelden, streaming is a great strength of Avro format so I'm very thankful fastavro streams. I've pushed a small branch of a "quick work around" as you suggest, at least this reverts it to "how it used to work" in the not very distant past, so it seems like a safe change. https://github.com/fastavro/fastavro/compare/master...jquast:regression-reader-stream?expand=1

I know how hard it is to find time to do FOSS work, I'm unable to keep abreast of my own public projects so I really appreciate any time you make to work on fastavro, great work and thanks again.

**Comment by scottbelden** [comment] 2018-10-31 22:42
@jquast I tried using your branch as a PR but it failed due to a few small issues. I put up another branch that is basically the same but with those issues fixed. If you are able, could you run https://github.com/fastavro/fastavro/pull/297 on your example and confirm? Otherwise I'll get it merged and released shortly.

**Comment by jquast** [comment] 2018-10-31 23:47
confirmed great, thanks

**Closed** 2018-10-31 23:54 UTC
